.github/workflows/python-package-conda.yml
Conda can take too long to solve.
=> Switch to pip for version control

.github/workflows/python-package-conda.yml, README.md
Start to evaluate what fraction of the code is untested
=> Add a coverage step to the CI

batdata/extractors/base.py, batdata/postprocess/integral.py, batdata/postprocess/tests/test_integral.py, requirements.txt
Scythe is the new name for our metadata extraction library
=> Switch to Scythe

.github/workflows/release.yml
Triggers when we publish a GitHub release
=> Add a release script

batdata/data.py
Both could be used for defining the location of a file
=> Support str or Path for filenames

batdata/data.py, batdata/schemas/cycling.py, batdata/tests/test_data.py
They are ignored in the current version 😬
=> Support saving cycle_stats in HDF5

batdata/data.py, tests/test_data.py
Related to #59
Doesn't _fix_ the problems with version changes, but I think we're too early stages to worry about backwards compatibility.
=> Warn if version of metadata is different, ignore failures

batdata/postprocess/cycle_stats.py, docs/features/cycle-times.ipynb, docs/post-processing.md, tests/postprocess/test_stats.py
Compute the start of a cycle and its duration.
To do:
=> Add methods for computing cycle times

batdata/exporters/__init__.py, batdata/exporters/ba.py, batdata/exporters/base.py, batdata/schemas/battery.py, batdata/schemas/cycling.py, docs/export.md, tests/conftest.py, tests/exporters/test_ba.py
Starts towards introducing an route for sending data to BatteryArchive and, eventually, the ROVI DataHub.
See #74
=> Introduce a base class, barebones exporter

batdata/data.py
=> Store schema with metadata

batdata/exporters/ba.py, tests/exporters/test_ba.py
Continue building conversions between our format and BatteryArchive's
=> Add cycle stats exporter

batdata/extractors/tIVT.py, batdata/postprocess/base.py, batdata/postprocess/timing.py, batdata/schemas/cycling.py, dev/environment.yml, docs/features/cycle-times.ipynb, tests/conftest.py, tests/postprocess/test_stats.py
=> Add ability to compute test_time and cycle_time

batdata/data.py, batdata/postprocess/integral.py, batdata/schemas/cycling.py, batdata/schemas/ontology.py, docs/Makefile, docs/conf.py, docs/export-schemas.py, docs/index.rst, docs/make.bat, docs/schemas.rst, docs/source/data.rst, docs/source/exporters.rst, docs/source/extractors.rst, docs/source/modules.rst, docs/source/postprocess.rst, docs/source/schemas.rst, pyproject.toml
Avoid people needing to understand pydantic, but it's still going to need some workshopping.
=> Add tabular renderings of the metadata schema

batdata/streaming.py, docs/source/modules.rst, docs/source/streaming.rst, docs/user-guide/dataset.rst, docs/user-guide/index.rst, docs/user-guide/streaming.rst, tests/test_stream.py
So that we can analyze files larger than what fits in memory.
=> Helper functions to stream data from HDF5

.github/workflows/gh-pages.yml
Fix issues related to pytables
=> Use Py3.10 in GHPages

battdat/io/hdf.py
I was saving the document twice for data tables
=> Save schema not document

README.md, battdat/consistency/current.py, battdat/schemas/__init__.py, battdat/schemas/cycling.py, docs/conf.py, docs/index.rst, docs/source/consistency.rst, docs/source/schemas.rst, docs/user-guide/schemas/export-schemas.py
And clean up a lot of the documentation while at it.
=> Move cycling metadata to subclass

battdat/io/hdf.py, battdat/schemas/column.py, docs/user-guide/dataset.rst, docs/user-guide/formats.rst, tests/io/test_hdf.py, tests/schemas/test_cycling.py
@c-randall would like to store interpolation points for the OCV and resistance values in each cycle.
=> Support array values in HDF5 format

battdat/streaming/hdf5.py
Adds a "write_mode" option to the HDFWriter class
=> Allow opening files in append mode during streaming

.github/workflows/gh-pages.yml
=> Upgrade to latest doc deployment

battdat/data.py, docs/user-guide/formats.rst, pyproject.toml, tests/test_data.py
We shouldn't be mixing tables and h5py, it's just confusing
=> Purge use of h5py

pyproject.toml
Get the version from the git tag
=> Switch to using autoversioning

battdat/data.py, battdat/io/hdf.py, battdat/postprocess/base.py, battdat/schemas/column.py, battdat/streaming/__init__.py, docs/user-guide/streaming.rst, tests/test_data.py, tests/test_stream.py
So that we can read both raw data and cycle_stats from a cell.
=> Add ability to stream multiple tables

battdat/postprocess/tagging.py, tests/postprocess/test_tagging.py
Creates and tests a `RawDataEnhancer` to determine if the cell is charging, discharging, or resting.
=> Enhancer to compute state

battdat/postprocess/tagging.py
Now, the enhancing of the dataset to add states allow the user to specify the maximum value of current to be considered a rest.
=> AddState allows user to specify max current for rest
